#string(REPLACE "." ";" VERSION_LIST ${MY_PROGRAM_VERSION})
#list(GET VERSION_LIST 0 MY_PROGRAM_VERSION_MAJOR)

file(ARCHIVE_CREATE
        OUTPUT ${TARGET_PATH}
        PATHS ${SOURCE_PATHS}
        FORMAT ${FORMAT}
)
