#ifndef _AMIGAMSG_H_
#define _AMIGAMSG_H_

enum amigamsg {
  AMIGAMSG_SETSUBSONG = 1,
  AMIGAMSG_SONG_END,
  AMIGAMSG_PLAYERNAME,
  AMIGAMSG_MODULENAME,
  AMIGAMSG_SUBSINFO,
  AMIGAMSG_CHECKERROR,
  AMIGAMSG_SCORECRASH,
  AMIGAMSG_SCOREDEAD,
  AMIGAMSG_GENERALMSG,
  AMIGAMSG_NTSC,
  AMIGAMSG_FORMATNAME,
  AMIGAMSG_LOADFILE,
  AMIGAMSG_READ,
  AMIGAMSG_FILESIZE,		// UADE_FILESIZE
  AMIGAMSG_TIME_CRITICAL,
  AMIGAMSG_GET_INFO,
  AMIGAMSG_START_OUTPUT,
  AMIGAMSG_ICON_LOAD,
  AMIGAMSG_ICON_TOOLTYPE,
  
 
  AMIGAMSG_AUDIO_DEV_OPEN = 50,
  AMIGAMSG_AUDIO_DEV_BEGINIO = 51,
  AMIGAMSG_AUDIO_DEV_ABORTIO = 52,
    
};

#endif
