.TH pacplay 1 "25 September 2007"
.SH NAME
pacplay \- play SBStudio PAC music modules
.SH SYNOPSIS
\fBpacplay\fP [ options ] \fIfilename\fP [ - ]
.SH DESCRIPTION
\fBpacplay\fP plays SBStudio PAC music modules.  pacplay will use the default
libao device for audio output unless a - character appears after
\fIfilename\fP, in which case it will write raw audio data to stdout (unless
it's a tty).
.SS Options
.TP
\fB-r \fIrate\fP
Set playback rate in Hz.  Legal values range from 4000 to 48000, but is
subject to output device limitations.  Default is 44100.
.TP
\fB-b \fIbits\fP
Set number of bits per sample.  Legal values are 8 and 16.  Default is 16.
.TP
\fB-c \fIchannels\fP
Set number of output channels.  Legal values are 1 and 2.  Default is 2.
.TP
\fB-h\fP
Display usage (synopsis).
.TP
\fB-q\fP
Quiet mode.  Only fatal errors are reported.
.SH FILES
/etc/libao.conf
~/.libao
.SH "SEE ALSO"
libao.conf(5)
.SH AUTHOR
Written by Thomas Pfaff <thomaspfaff@users.sourceforge.net>
.SH BUGS
Please report any bugs you encounter!  Thank you.
