.TH "debug68" 1 "29 Aug 2003" "sc68-tools-manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
debug68 \- Create and debug sc68 files.
.SH "AUTHOR"
.PP
Copyright (C) 1998-2003 Benjamin Gerard <ben@sashipa.com>
.PP
This program is free software.
.SH "DATE"
.PP
2003
.SH "SYNOPSIS"
.PP
debug68 [options ... ] 
.PP
debug68 debug68
.SH "OPTIONS"
.PP
.IP "\(bu" 2
\fB--help\fP Display this message and exit. 
.PP

