.TH "unice68" 1 "29 Aug 2003" "sc68-tools-manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unice68 \- Ice depacker based on 68000 ICE 2.40 original.
.SH "AUTHOR"
.PP
Copyright (C) 1998-2003 Benjamin Gerard <ben@sashipa.com>
.PP
This program is free software.
.SH "DATE"
.PP
1998
.SH "SYNOPSIS"
.PP
unice68 [option ...]  
.SH "OPTIONS"
.PP
.IP "\(bu" 2
\fB--help\fP Display this message and exit. 
.IP "\(bu" 2
\fB-v\fP Be verbose. 
.IP "\(bu" 2
\fB-q\fP Keep quiet
.PP
.SH "BUGS"
.PP
None has been reported. Report to \fIbug@sashipa.com\fP.
.SH "SEE ALSO"
.PP
\fIas68\fP, \fIdebug68\fP, \fIinfo68\fP, \fIsc68\fP, \fIsourcer68\fP, \fIunice68\fP 
